@startuml
left to right direction
class "Administrador" as A <<actor>>
class "Formulário de Custos" as B <<boundary>>
class "Configuração de Custos" as C <<control>>
class "Parametro" as PM <<entity>>
A --> B : informa preço e rendimento
B --> C : solicita parametrização
C --> PM : lê versão anterior
C --> PM : registra versão e custo/km
C --> B : mostra valores vigentes
@enduml
